### ISSUE TITLE
Php7 & utf8 compatibility

### ISSUE THREAD

**Issue by qdelettre** [wesnick/fdf-utility#3]
Hi,

I would like to know about fdf-utility php7 & utf8 compatibility.

Thanks

**Comment by wesnick** [comment]
Hi,
I updated the tested versions of PHP to 5.6 and 7, both pass in travis-ci.  UTF8 compatibility is a much more tricky proposition.  For starters, the library uses ascii conversion functions.  Even if you could pass utf-8 encoded entities to an FDF file, the only tool I know of to generate PDF forms from them, PDFTK, seems to just ignore them.  

Checkout some background info here:
http://stackoverflow.com/questions/6047970/weird-characters-when-filling-pdf-with-pdftk
